trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    export NODE_OPTIONS=--openssl-legacy-provider
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'NotesService'
    appType: 'webAppLinux'
    appName: 'Notes'
    package: '$(System.DefaultWorkingDirectory)/build'
    runtimeStack: 'NODE|22-lts'
  displayName: 'Deploy to Azure App Service'

- script: |
    cd src/server
    npm install
    displayName: 'Install Backend Dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'NotesService'
    appType: 'webAppLinux'
    appName: 'Notes-Backend' # Replace with your backend App Service name
    package: '$(System.DefaultWorkingDirectory)/src/server'
    runtimeStack: 'NODE|22-lts'
  displayName: 'Deploy Backend to Azure App Service'